name = "Covid Fighters"
description = "Covid Fighters have built a technology consortium to test Covid19 from a mobile unit to test whether or not a test subject is infected and contagious. The actual test takes only a few hours and the mobile unit can be deployed in a matter of days."
stars = 5
sectionID = 1
rank = 15
url = "https://www.consciousinternet.org/#/projects/CovidFighters"
