name = "Vlinder"
description = "Vlinder means butterfly in Dutch. We believe in the butterfly effect of a small behavioral change in a connected world. We envision the Vlinder app as a tool empowering you to make those changes. You will be able to know and mitigate your personal environmental footprint by investing in high-impact products and connecting with sustainability-focused businesses."
stars = 5
sectionID = 1
rank = 14
url = "https://www.consciousinternet.org/#/projects/Vlinder"
