name = "Dash"
description = "Dash is an open source peer-to-peer cryptocurrency with a strong focus on the payments industry. Dash offers a form of money that is portable, inexpensive, divisible and fast. It can be spent securely both online and in person with only minimal transaction fees. Based on the Bitcoin project, Dash aims to be the most user-friendly and scalable payments system in the world."
stars = 5
sectionID = 2
rank = 6
url = "https://wiki.threefold.io/#/dash"
