name = "Wayki Chain"
description = "WaykiChain is focused on developing its own technology, bottom public chain layer and as well corresponding to that an ecosystem which will foster technology research and development, as well as project operation."
stars = 5
sectionID = 2
rank = 7
url = "https://wiki.threefold.io/#/waykichain"
