name = "Earth Project"
description = "Every child deserves an education. We have built a community of thousands of teachers globally which allows us to connect to children and teachers in refugee camps. Our platform allows to train teachers in refugee camps (67% of which haven't completed secondary education) and have interactions between refugee students and students globally changing their mindset and fighting polarization."
stars = 5
sectionID = 1
rank = 11
url = "https://www.consciousinternet.org/#/projects/EarthProject"
