name = "Zetako"
description = "For many years, research has been focused on increasing the capacity of 40 year old compressions algorithms (LZW) instead of developing new approaches. We believe that the world’s exponential data creation, processing and storage needs cannot be met with old optimized algorithms. To use Albert Einstein's words: “We cannot solve our problems with the same thinking we used when we created them."
stars = 5
sectionID = 1
rank = 9
url = "https://www.consciousinternet.org/#/projects/Zetako"
