name = "Green Edge"
description = "Green Edge Sustainable Development is planning to offer affordable, distributed and decentralised storage and computing capacity for developers and partner telecom companies in Africa"
stars = 5
sectionID = 1
rank = 8
url = "https://www.consciousinternet.org/#/projects/Green%20Edge%20Sustainable%20Development"
