name = "Skale Labs"
description = "SKALE is an elastic blockchain network that gives developers the ability to easily provision highly configurable fully decentralized chains that are instantly compatible with Ethereum."
stars = 5
sectionID = 2
rank = 8
url = "https://wiki.threefold.io/#/skalelabs"
