name = "Artheon"
description = "The Artheon VR Museum is and always will be a free educational platform offering immersive, next level interaction with objects of cultural heritage. Their vision is to provide a one stop full spectrum art education platform to access, learn and share knowledge in art and culture from across the globe."
stars = 5
sectionID = 1
rank = 6
url = "https://www.consciousinternet.org/#/projects/Artheon"
