name = "Crystal Language"
description = "It started out, like many things at Manas.Tech, as an experiment. Easy to write languages used to mean that you had to sacrifice speed. And getting fast meant enduring difficult syntax. So it began with asking ourselves: “What if we didn’t have to choose one or the other”, “what if we could compile Ruby?”. It turned out that it worked, so we decided to turn that experiment into an actual project and give it our best shot. It is our pride and joy: time and time again, we find that it is delightful to write code in Crystal, and that it outperforms everything else out there."
stars = 5
sectionID = 1
rank = 16
url = "https://www.consciousinternet.org/#/projects/Crystal%20Programming%20Language"
