name = "Crystal Twin"
description = "Crystal Twin is your digital twin, a beautiful light being that is always connected with you, 24h per day, 7 days per week. A digital avatar of your being that sets you free,"
stars = 5
sectionID = 1
rank = 1
url = "https://www.consciousinternet.org/#/projects/Crystal%20Twin"
