name = "Crystal Twin"
description = "Take Action Global (TAG) was created to inspire change by providing opportunities for students around the world to take action on social good causes through education. In a pilot program, ThreeFold is partnering with TAG on the Kakuma Project, a TAG-led education initiative in the Kakuma refugee camp in Kenya, offering financial commitment (funds from the IEO) and the support of technology. Together, TAG and ThreeFold can bring education opportunities to hundreds of millions or more around the world."
stars = 5
sectionID = 1
rank = 1
url = "https://www.consciousinternet.org/#/projects/Crystal%20Twin"
