name = "Crystal Home"
description = "Our planet needs a different approach to housing. The construction industry is one of the most polluting sectors out there, and we are changing it. We are building circular and fully self-sufficient homes that make housing construction affordable and sustainable without compromising on quality. All of the construction materials are second hand and refurbished for a new life."
stars = 5
sectionID = 1
rank = 10
url = "https://www.consciousinternet.org/#/projects/Crystal%20Home"
