name = "Generation Blue"
description = "We enable the shift to an Earth Positive economy based on reciprocity, where every act of consumption is met with an opposite act of regeneration and protection of nature. Our blockchain based ecosystems accounting system enables anyone to get Earth Positive by investing in environmental impact tokens."
stars = 5
sectionID = 1
rank = 12
url = "https://www.consciousinternet.org/#/projects/Generation%20Blue"
