
name = "Cicolab"
description = "Social is a collaboration network built for the new internet. It leverages blockchain technology to provide an economic alternative to surveillance capitalism, and decentralized cloud providers to empower users with self sovereign data and digital asset ownership."
stars = 5
sectionID = 1
rank = 18
url = "https://consciousinternet.org/#/projects/Collective%20Intelligence%20Collaboratory"
