name = "Money of Good"
description = "Money of Good is a socioeconomic platform that uses disruptive proof-of-meditation technology (neurofeedback+blockchain) to offer people the chance to earn money as a reward for practicing meditation, improving their health, raising consciousness while fostering a new fair and sustainable economic model: the conscious economy of the common good. We love this approach because the reward mechanism based on proof-of-meditation makes it possible to run the most effective and reliable basic income program globally"
stars = 5
sectionID = 1
rank = 13
url = "https://www.consciousinternet.org/#/projects/Money%20of%20Good"
